<Project>
  <PropertyGroup>
    <ModName>ShadowCulling</ModName>
    <RepositoryURL>https://github.com/zhu-rengong/barotrauma-mod-shadowculling</RepositoryURL>
    <UsePublicizedAssemblies>true</UsePublicizedAssemblies>
  </PropertyGroup>

  <Import Project="UserBuildData.props" />

  <Import Project="SharedProject\SharedProject.projitems" Label="Shared" />
  <Import Project="SharedProject\SharedItems.props" />

  <Target Name="CopyFiles" AfterTargets="Build">
    <ItemGroup>
      <FilesToCopy Include="$(TargetDir)$(TargetName).dll" />
      <FilesToCopy Include="$(TargetDir)$(TargetName).deps.json" />
      <FilesToCopy Include="$(TargetDir)$(TargetName).pdb" />
    </ItemGroup>
    <Copy SourceFiles="@(FilesToCopy)" DestinationFolder="$(MSBuildThisFileDirectory)ContentPackageBuilder\Content\bin\$(PlatformName)" />
  </Target>
</Project>